name: Deploy Static Website to GH-Pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Deploying to Gh-Pages
        uses: ./.github/actions/deploy-gh-pages
        env:
          GH_USERNAME: reiniergs
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
    
     
   
